// Code generated by Slice Machine. DO NOT EDIT.

import Header from './Header';
import TextBlock from './TextBlock';

export {
	Header,
	TextBlock,
};

export const components = {
	text_block: Header,
	text_block: TextBlock,
};
