// Code generated by Slice Machine. DO NOT EDIT.

import Code from './Code';
import Image from './Image';
import Text from './Text';

export {
	Code,
	Image,
	Text,
};

export const components = {
	code: Code,
	image: Image,
	text: Text,
};
