// Code generated by Slice Machine. DO NOT EDIT.

import Code from './Code';
import Image from './Image';
import Text from './Text';
import TextTitle from './TextTitle';

export {
	Code,
	Image,
	Text,
	TextTitle,
};

export const components = {
	code: Code,
	image: Image,
	text: Text,
	text_title: TextTitle,
};
